name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  

    env:
      Solution_Name: SoundMaker.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: test/SoundMakerTests.csproj               # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Execute build with warn as error
      run: dotnet build --no-restore /warnaserror

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test